import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import StoreProvider from "@/Providers/StoreProvider";
// import { Raleway } from "@next/font/google";
import { Raleway } from "next/font/google";
const raleway = Raleway({
  subsets: ["latin"],
  weight: ['100','400','500']
});


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Nezztar",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`font-[500] ${raleway.className}`}>
        <StoreProvider>{children}</StoreProvider>
      </body>
    </html>
  );
}
